[2025-05-12T23:14:38.109+0500] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: data_pipeline_dag.track_raw_data manual__2025-05-12T18:10:53.946844+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-05-12T23:14:38.113+0500] {local_task_job_runner.py:154} INFO - Task is not able to be run
